name: client
description: A new Flutter Boilerplate Example project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  #ui utilities  
  cupertino_icons: ^1.0.2
  lottie: ^2.1.0
  loading_overlay: ^0.3.0
  intl: ^0.17.0
  flutter_svg: ^1.1.6
  flutter_rating_bar: ^4.0.1
  chewie: ^1.3.6
  flutter_timer_countdown: ^1.0.5
  
  #Configuration
  flavor: ^2.0.0
  flutter_dotenv: ^5.0.2
  

  #Code generation
  injectable: ^1.5.3

  #Network
  dio: ^4.0.6
  retrofit: ^3.3.1
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0

  #Cache
  shared_preferences: 2.0.0-nullsafety  
  
  
  
  # Service Locator 
  get_it: 7.2.0
  path: any

  #Core utilities
  logger: ^1.1.0
  card_swiper: ^2.0.4

  #videoos
  video_player: ^2.4.10
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

  #Flutter analyze
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.1.0+1
  injectable_generator:  ^1.5.4

  #Network
  retrofit_generator: ^4.2.0
  freezed: ^2.3.0
  json_serializable: ^6.5.4

  #State managment
  rxdart: ^0.27.7
  provider: ^6.0.4





flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/env/.env.prod
    - assets/env/.env.test
    - assets/env/.env.dev
    - assets/env/
    - assets/images/
    - assets/icons/
    - assets/lottie/
