name: client
description: A new Flutter Boilerplate Example project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2 
  flavor: ^2.0.0
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
  injectable: ^1.5.3
  dio: ^4.0.6
  get_it: 7.2.0
  path: any
  retrofit: ^3.3.1
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  loading_overlay: ^0.3.0
  logger: ^1.1.0
  shared_preferences: 2.0.0-nullsafety
  flutter_rating_bar: ^4.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  injectable_generator:  ^1.5.4
  retrofit_generator: ^4.2.0
  freezed: ^2.3.0
  json_serializable: ^6.5.4
  rxdart: ^0.27.7
  provider: ^6.0.4
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/wtechLogo.png"  
flutter:
  generate: false
  uses-material-design: true
  assets: 
    - assets/env/.env.prod
    - assets/env/.env.test 
    - assets/env/.env.dev
    - assets/env/
    - assets/images/
    - assets/icons/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
